// import Link from "next/link";

// import { LatestPost } from "@/app/_components/post";
// import { getServerAuthSession } from "@/server/auth";
import { HydrateClient } from "@/trpc/server";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  // const hello = await api.post.hello({ text: "from tRPC" });
  // const session = await getServerAuthSession();

  return (
    <HydrateClient>
      <main>Jo</main>
    </HydrateClient>
  );
}
